version: '3.9'
services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - chat-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/data

  event-bus:
    image: redislabs/redis
    ports:
      - '12000:12000'
      - '8443:8443'
      - '9443:9443'
    privileged: true
    cap_add:
      - SYS_RESOURCE

volumes:
  chat-db:
